name: 'fabric_table_materialization'
version: '1.0.0'

profile: 'fabric_table_materialization'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fabric_table_materialization:
    +materialized: table
    +meta:
      log_to_stdout: true
    intermediate:
      +schema: intermediate
    stage:
      +schema: stage
      +materialized: view
      
seeds:
  +full_refresh: True
  +schema: seed
